apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: init-container
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: init-container
    spec:
      containers:
      - name: application
        image: busybox
        command: ['sh', '-c', 'echo The app is running! && sleep 3600']
      initContainers:
      - name: init-container
        image: bash
        command: ['bash', '-c', 'for i in {1..10};do echo $i; sleep 1; done;']
